### ISSUE TITLE
kafka2influxdb install ExecStart has double “/”

### ISSUE THREAD

**Issue by walnut-tom** [stephane-martin/kafka2influxdb#11]
with fedora 25, run _kafka2influxdb install --prefix=/opt/app/kafka2influxdb_ , but _systemctl status kafka2influxdb.service_ see double **“/”**:

......
ExecStart=//opt/app/kafka2influxdb/bin/kafka2influxdb ...
......

**Comment by stephane-martin** [comment]
Thanks for reporting. I can't reproduce so far. Do you use the git HEAD version ? And what is your shell (bash/zsh) ?

**Comment by walnut-tom** [comment]
I'm sorry, I tried again today. I checked the history order. I was wrong
