### ISSUE TITLE
Vendored Sarama-Cluster Out of Date

### ISSUE THREAD

**Issue by ryanjeffries** [stephane-martin/kafka2influxdb#16]
Hello, there is a bug in the current vendored sarama-cluster that is included in this repo. This version does not commit the correct offset of topics in kafka when there is only 1 record in a partition, instead will default to -1. This has been fixed in their latest version. By the way what vendoring tool are you using?

**Comment by stephane-martin** [comment]
The referenced commit should fix that.

I use govendor. No particular reason. Just had to pick one.

**Comment by ryanjeffries** [comment]
thank you
