### ISSUE TITLE
Per topic format

### ISSUE THREAD

**Issue by stephane-martin** [stephane-martin/kafka2influxdb#9]

**Comment by walnut-tom** [comment]
Per topic format and Independent _**influxdb**_ configuration, Independent configuration.

**Comment by stephane-martin** [comment]
Please see 401fefc8cc8f69248682feb9324f119cd1d6aa79

**Comment by walnut-tom** [comment]
Only last configuration is used for each topic

**Comment by stephane-martin** [comment]
That's intended. See comments with your PR https://github.com/stephane-martin/kafka2influxdb/pull/12
